### ISSUE TITLE
TODO : 모든 API 검토 후 검증 로직 추가

### ISSUE THREAD

**Issue by mokhs00** [MARS-crew/shower-chat-be-express#2]
빠른 진행을 위해서 우선적으로 빠른 API 개발 이후에 검증 로직을 추가합니다.
검증 로직 추가는 프로그램에 영향이 없도록 코드를 수정하면서 진행합니다.

- [ ] 1차 기능 API 개발
- [ ] API 검토 
- [ ] API 검토 후 현재 이슈 댓글로 TODO LIST 생성
- [ ] 검증 로직 추가해서 TODO LIST 해결하기
